### ISSUE TITLE
KOR Support

### ISSUE THREAD

**Issue by Committee** [smealum/ninjhax2.x#1]
Possible for the hax to support KOR 3DS systems? Menuhax and (I believe,  may be wrong) Broswerhax currently support KOR all it needs now is the payload.

**Comment by Committee** [comment]
@Sniffynose does your commit support KOR systems now?

**Comment by Sniffynose** [comment]
No additional payloads have been added/removed, so if it doesn't work with Smea's original, it won't work with any of the current forks. I don't personally have a KOR system to be able to test sadly.

**Comment by kitling** [comment]
If I understand correctly, this was fixed with #7 and #10.
