### ISSUE TITLE
Broken in 11.1.0-34?

### ISSUE THREAD

**Issue by weirdal3333** [smealum/ninjhax2.x#14]
Last time, I just renamed the file to the menu version (9.9.0-?? to 11.0.0-33) and it worked.

I have the current 11.0 ropbin, and I renamed it, but it just crashes.
Specs:
O3ds + luma softmodded + nand System menu 11.1.0-34

**Comment by weirdal3333** [comment]
This was probably why servers were down so long on 9/12/2016

**Comment by ihaveamac** [comment]
*hax still needs updating for 11.1.

**Comment by weirdal3333** [comment]
Lol last time it was the name, I have luma, I can bugtest!

**Comment by weirdal3333** [comment]
Sorry, I also use hblauncher_loader v1.2 -- updating... but it still doesn't work.

**Comment by weirdal3333** [comment]
Yay thanks @yellows8 :D

**Comment by yellows8** [comment]
@ https://twitter.com/smealum/status/775915581379706880
