### ISSUE TITLE
Otherapp 11.2

### ISSUE THREAD

**Issue by jy-roda** [smealum/ninjhax2.x#15]
Hi,
When will otherapp payload be available for 11.2 ?
Thanks

**Comment by d3m3vilurr** [comment]
probably 11.1 payload can use 11.2

**Comment by jy-roda** [comment]
I think 11.2 introduced PASLR, hence the need for an updated payload.

**Comment by yellows8** [comment]
"11.1 payload can use 11.2" indeed
